# This is a simple powershell command execution task for Dev Box.

$schema: 1.0
name: powershell
description: Execute a powershell command.
author: Microsoft Corporation
timeout: 3600
parameters:
  command:
    type: string
    default: ""
    required: true
    description: The command to execute.
